# Generated by Django 4.2.11 on 2024-05-30 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_main_app", "0009_template_formats"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateHtmlRendering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_rendering", models.TextField(blank=True)),
                ("detail_rendering", models.TextField(blank=True)),
                (
                    "template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_main_app.template",
                    ),
                ),
            ],
        ),
    ]
