# Generated by Django 4.2.16 on 2025-02-28 16:55

import core_main_app.commons.validators
import core_main_app.utils.storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_main_app", "0011_blob_processing_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blobprocessingmodule",
            name="run_strategy",
        ),
        migrations.AddField(
            model_name="blobprocessingmodule",
            name="run_strategy_list",
            field=models.JSONField(
                default=list,
                null=True,
                validators=[
                    core_main_app.commons.validators.RunStrategyValidator()
                ],
            ),
        ),
    ]
