# Generated by Django 4.2.21 on 2025-05-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_main_app", "0012_update_processing_module_run_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="file_history",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="file_history",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="xsltransformation",
            name="file_history",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
