# Generated by Django 5.2.8 on 2026-02-09 20:48

from django.db import migrations, models

import core_main_app.commons.validators
import core_main_app.utils.storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ("core_main_app", "0013_file_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataProcessingModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None, max_length=256, unique=True
                    ),
                ),
                (
                    "run_strategy_list",
                    models.JSONField(
                        default=list,
                        null=True,
                        validators=[
                            core_main_app.commons.validators.RunStrategyValidator()
                        ],
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("processing_class", models.CharField(max_length=256)),
                (
                    "template_filename_regexp",
                    models.CharField(
                        default=".*",
                        max_length=250,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
